#%RAML 1.0 DataType
type: object
properties:
  orderId: string
  customerId: integer
  status: 
    enum: [PENDING, SHIPPED, DELIVERED, CANCELLED]
  items:
    type: array
    items:
      properties:
        bookId: integer
        quantity: integer
  totalAmount: number